---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wap-admin
  namespace: wap-admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: wap-admin
subjects:
- kind: ServiceAccount
  name: wap-admin
  namespace: wap-admin
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
